title: Stefanã§ã™
logo: /images/bowl2_2x.png
email: stefandesu@exo.pm
description: >- # this means to ignore newlines until "baseurl:"
  Developer (mainly Swift, Python, web). Climber. Japan Enthusiast.
twitter_username: stefandesu
github_username:  stefandesu
