remote_theme: stefandesu/exo-blog-theme
title: Stefanです
logo: /images/bowl2_2x.png
email: stefandesu@exo.pm
description: Developer (mainly Swift, Python, web). Climber. Japan Enthusiast.
twitter_username: stefandesu
github_username:  stefandesu
navigation:
  -
    name: Home
    url: /
  -
    name: About
    url: /about/
footer: |
  Copyright ©2018 Stefan. [Impressum](/impressum/)
  <br>Logo made by my flatmate Salo. Thanks. :3 
