remote_theme: stefandesu/exo-blog-theme
title: Stefan です
logo: /images/bowl2_2x.png
email: stefandesu@exo.pm
description: Who am I, actually?
twitter_username: stefandesu
github_username:  stefandesu
permalink: pretty
plugins: [jekyll-paginate, jekyll-redirect-from]
paginate: 10
paginate_path: "/page/:num/"
defaults:
 -
   scope:
     path: ""
     type: posts
   values:
     layout: post
 -
   scope:
     path: ""
   values:
     layout: page
navigation:
  -
    name: Home
    url: /
  -
    name: About
    url: /about/
  -
    name: Contact
    url: /contact/
footer: |
  Copyright ©2020 Stefan. [Impressum](/impressum/).
  <br>Logo made by my flatmate Salo. Thanks. :3
